name: Trigger CI
on:
  push:

jobs:
  update-release-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Trigger CI with latest commit details
        run: |
          GITHUB_MESSAGE="${{ github.event.head_commit.message }}"
          # if [ -z "$GITHUB_SHA" ]; then
          #   GITHUB_SHA=$(git rev-parse HEAD)
          #   GITHUB_MESSAGE=$(git log --format=%B -n 1 ${GITHUB_SHA})
          # fi
          echo $GITHUB_SHA
          echo $GITHUB_MESSAGE
          echo $GITHUB_MESSAGE
          gh workflow run --repo SaphMB/cicd-test "Release Kratix" -f sha=$GITHUB_SHA -f message=$GITHUB_MESSAGE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}